## Reshape in numpy

In [1]:
import numpy as np

# to keep the example easy to view, we use 10 examples of pictures.  Each picture is of size 4x4 pixels, and each pixel contains 3 (r,g,b) values
# we first fill an array with sequential 480 entries (10*4*4*3) and then reshape it into an 10x4x4x3 array
a=np.arange(10*4*4*3).reshape(10, 4, 4, 3)
print(a.shape)
print(a)

# we can reshape arrays using .reshape method
# array axis are numbered from 0 and accessed through .shape method
# if a specific axis is specified to .reshape, that axis is preserved and the rest of the axis' are reshaped/flattened
# a -1 argument tells numpy to figure out the dimensions of reshaped axis 

# flatten the innermost axis (the r,g,b values), which are already flat, so this operation does nothing
aflat=a.reshape(a.shape[0],a.shape[1],a.shape[2],-1)
print(aflat.shape)
print(aflat)

# flatten the innermost two axis (r,g,b values in each pixel row). 4x3 gets flattened to 12 color values
aflat=a.reshape(a.shape[0],a.shape[1],-1)
print(aflat.shape)
print(aflat)

# flatten the innermost three axis (r,g,b values in each pixel row, reading left to right and top to bottom). 4x4x3 gets flattened to 48 values.  this operation flattens each individual image
aflat=a.reshape(a.shape[0],-1)
print(aflat.shape)
print(aflat)

# at this point, the rows have 'examples' (the training or test cases) and columns have the 'features' (the color values).  to get the features in rows and examples in columns, we transpose the matrix using the .T method
aflatt=aflat.T
print(aflatt.shape)
print(aflatt)

# fun exercise
# to create random pixel noise to test your trained network, try the following
# x_test=np.random.randint(255,size=(64*64*3,209))
# print(x_test.shape)
# print(x_test)

(10, 4, 4, 3)
[[[[  0   1   2]
   [  3   4   5]
   [  6   7   8]
   [  9  10  11]]

  [[ 12  13  14]
   [ 15  16  17]
   [ 18  19  20]
   [ 21  22  23]]

  [[ 24  25  26]
   [ 27  28  29]
   [ 30  31  32]
   [ 33  34  35]]

  [[ 36  37  38]
   [ 39  40  41]
   [ 42  43  44]
   [ 45  46  47]]]


 [[[ 48  49  50]
   [ 51  52  53]
   [ 54  55  56]
   [ 57  58  59]]

  [[ 60  61  62]
   [ 63  64  65]
   [ 66  67  68]
   [ 69  70  71]]

  [[ 72  73  74]
   [ 75  76  77]
   [ 78  79  80]
   [ 81  82  83]]

  [[ 84  85  86]
   [ 87  88  89]
   [ 90  91  92]
   [ 93  94  95]]]


 [[[ 96  97  98]
   [ 99 100 101]
   [102 103 104]
   [105 106 107]]

  [[108 109 110]
   [111 112 113]
   [114 115 116]
   [117 118 119]]

  [[120 121 122]
   [123 124 125]
   [126 127 128]
   [129 130 131]]

  [[132 133 134]
   [135 136 137]
   [138 139 140]
   [141 142 143]]]


 [[[144 145 146]
   [147 148 149]
   [150 151 152]
   [153 154 155]]

  [[156 157 158]
   [159 160 161]
   [162 163 164]
   [165 166 167]]

