### Difference between reshape & resize

In [24]:
import numpy as np

In [22]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
a.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [23]:
a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
a.resize(2,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

**Both these functions are used to change the size of the array. resize function changes the original size, while reshape only change the duplicate version of the original array**

### Differences between ravel & flatten

**flatten(order='C')**

**order : {‘C’,’F’, ‘A’, ‘K’}, optional**

The elements of a are read using this index order. **‘C’ means to index the elements in row-major**, C-style order, with the last axis index changing fastest, back to the first axis index changing slowest. **‘F’ means to index the elements in column-major**, Fortran-style order, with the first index changing fastest, and the last index changing slowest. Note that the ‘C’ and ‘F’ options take no account of the memory layout of the underlying array, and only refer to the order of axis indexing. **‘A’ means to read the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise**. **‘K’ means to read the elements in the order they occur in memory**, except for reversing the data when strides are negative. 

**By default, ‘C’ index order is used.**

In [13]:
a = np.arange(6).reshape(2,3)
a.flatten()

array([0, 1, 2, 3, 4, 5])

In [14]:
a.ravel()

array([0, 1, 2, 3, 4, 5])

In [15]:
a.flatten('F')

array([0, 3, 1, 4, 2, 5])

In [16]:
a.ravel('F')

array([0, 3, 1, 4, 2, 5])

In [18]:
x = np.array([[1,2],[3,4]])
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
a.flatten()

array([0, 1, 2, 3, 4, 5])

In [20]:
a.flatten()[...] = 1
a

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
a.ravel()[...] = 1
a

array([[1, 1, 1],
       [1, 1, 1]])

**Both these functions are used to change the dimension of the array. ravel function changes the original size, while flatten only change the duplicate version of the original array**

### squeeze function

can only change a vector to a matrix with row=1

In [25]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [27]:
# doesn't work for matrix with col!=0
np.squeeze(a)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
b=np.arange(3)#.reshape(3,1)
b

array([0, 1, 2])

In [33]:
b=b.reshape(3,1)
b

array([[0],
       [1],
       [2]])

In [34]:
np.squeeze(b)

array([0, 1, 2])